### ISSUE TITLE
Clarification for example 2

### ISSUE THREAD

**Issue by wamserma** [jmgilman/std-example#1]
First: Thank you for you explanation of `std`. It was the first answer to "what is this thing?" I understood.

I have a question, thou: Is there a particular reason that a list-of-lists-of-strings is used here:
https://github.com/jmgilman/std-example/blob/6e1855da47556c90dc6d4faa07c05e188e9f5380/part2/flake.nix#L85
while this is a list-of-strings:
https://github.com/jmgilman/std-example/blob/6e1855da47556c90dc6d4faa07c05e188e9f5380/part2/flake.nix#L95

**Comment by jmgilman** [comment]
Hi,

Glad I was able to help you. This is actually an artifact from copying some stuff over from another one of my projects. Your second example above is the more concise and correct usage. If I had multiple places I want to harvest under `packages`, then I would use:

```nix
packages = std.harvest inputs.self [ [ "std-example" "apps" ] ["std-example" "apps2"] ]; 
```

I'll fix this to be less confusing. Thanks for the feedback!
